### ISSUE TITLE
Reference object 

### ISSUE THREAD

**Issue by kkrishnan90** [vikz91/generator-mongoose#12]
Hi,
This seems to be the best API generator. However, can you help me on how to declare references between models through runtime ? Like I have users as a model which I want to reference it to employee model.

**Comment by vikz91** [comment]
Hi,

Correct me if I am wrong but as I understand, you can put a 'ref' option in
the model to assign a reference.

E.g

{
  employee: {
      user: { type: String, ref: 'User'}
  }
}

**Comment by kkrishnan90** [comment]
Yeah that's what I wanted. But how do I do it in CLI itself as shown in the YouTube video tutorial ? Like declaring model name and it's attributes with data type.

**Comment by vikz91** [comment]
The latest code does not have the ref to be appended automatically. I will
be pushing the bleeding edge branch in few days which does exactly what you
need.

For the time being, you need to add the ref manually. Hope it helps.

**Comment by kkrishnan90** [comment]
Please let me know once you're done updating the master branch with this. Till then, perhaps I haven't got a choice apart from updating models manually.

**Comment by vikz91** [comment]
Hi, This issue has been resolved, please find the feature in the latest v0.5.0. The latest build has been re-written from scratch.
Just use `$ yo restgoose:schema "item|name:String, category:String>category"` to point your category field in item collection to _id field of category collection.
