### ISSUE TITLE
Object name error

### ISSUE THREAD

**Issue by kkrishnan90** [vikz91/generator-mongoose#14]
The object name for POST as mentioned in the tutorial isn't the ```"article"```
Rather, it never works with the following JSON during HTTP POST,
 ```
{
	"article":{
  "content": "Content here 3"
}
}
```
Throws me the following error for the above request
```
{
    "status": "error",
    "data": "Invalid data model provided",
    "message": "There was an error saving this data."
}
```

On the other hand, if I change the request to be like ,

```
{
	"data":{
  "content": "Content here 3"
}
}
```

I get a proper response from the server back, 

```
{
    "status": "success",
    "data": {
        "_id": "5bfc32d8f21e822d804c6ec3",
        "content": "Content here 3",
        "created": "2018-11-26T17:52:24.098Z",
        "__v": 0
    },
    "message": null
}
```

Isn't this contradictory to what is shown in the tutorial or the ReadMe description ?
I had figured this out, from the test cases that is auto generated. :+1:  for this feature

**Comment by vikz91** [comment]
Hi,
 thanks for pointing that out.
Although that was given as an example but I guess I will have to format the
tutorials in a more clear way.

**Comment by kkrishnan90** [comment]
So is the way I mentioned intended ? Or is this a bug that needs a fix ?

**Comment by vikz91** [comment]
The doc states 'article' as example. So the intended way is 'data' as you
can see from tests.

**Comment by kkrishnan90** [comment]
But wouldn't it be a good convention to state the same as the object name rather than 
```
data
```
