### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by jamespsterling** [vikz91/generator-mongoose#15]
```sh
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-restgoose/generators/app/templates/.gitignore
```

**Comment by vikz91** [comment]
Hi,
Can you please tell which version of the generator are you using and steps to reproduce the bug?
I just tried with the latest master one its not giving me any errors.

**Comment by jamespsterling** [comment]
The latest version of the repo as of 2 days ago.

**Comment by OlafRocket** [comment]
.gitignore is missing from the templates folder.
You can find it in the github repository. Simply copy it in your installation folder (check the first line of the error message) and it should work.

**Comment by vikz91** [comment]
Hi,
Thanks for reporting the issue.
I have tested it in many other different devices and in different occasions and it seems I am not able to replicate the issue. I have also checked the source code and I have uploaded this screenshot of the existence of the file. Also, TravisCI does not complain anything on its end for the test cases.
<img width="1052" alt="screenshot 2019-01-30 at 10 17 23 pm" src="https://user-images.githubusercontent.com/2017413/51997624-1af2c180-24dd-11e9-9380-fb33d0a5dbab.png">

As of now, I am closing this issue and awaiting more people to comment on it. Meanwhile, you can make sure that the branch and version is latest and please try it on a different device and let me know if the issue still persists.

**Comment by OlafRocket** [comment]
Some more information: I am working in Windows 10, yo and restgoose installed via npm, not git

**Comment by alwindeleon** [comment]
im still getting this error on my mac

**Comment by santoslucasls** [comment]
I'm having a similar error:


? Database Name authentication
? Host Url authentication.fastinvoice.com
? Use User Authentication Yes
Initialized empty Git repository in /Users/santoslucasls/workspace/fast_invoice/.git/
events.js:173
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-restgoose/generators/app/templates/.gitignore
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-restgoose/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-restgoose/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at module.exports.writing (/usr/local/lib/node_modules/generator-restgoose/generators/app/index.js:70:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-restgoose/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/generator-restgoose/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-restgoose/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-restgoose/node_modules/yeoman-generator/lib/index.js:425:13
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-restgoose/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (internal/timers.js:439:21)
Lucass-MacBook-Pro:fast_invoice santoslucasls$
