### ISSUE TITLE
JWT support

### ISSUE THREAD

**Issue by haroondilshad** [vikz91/generator-mongoose#2]
Hi. Can you please show how to use JWT which come pre-loaded with it?

**Comment by vikz91** [comment]
Hi RonCan,
unfortunately, I have removed the JWT support as a lot of people wanted to implement their own mechanisms.  
Btw, using JWT is pretty simple. ON the server side, use it as middle-were with Express to check on each received request. Have a totally different endpoint of your REST API to create tokens with the JWT and send them as response. So, all the other end points ( routes) would expect a jwt Token in the header. use https://github.com/auth0/express-jwt

**Comment by vikz91** [comment]
Since there is nothing I can help you with regarding JWT, I am closing the issue.  Hope the link helps.
