### ISSUE TITLE
Mixed datatype

### ISSUE THREAD

**Issue by azizasm** [vikz91/generator-mongoose#5]
generator-restgoose having issue to generate Mixed datatype . Any suggestion to fix this ? 

'yo restgoose:schema "patient|name:String,gender:String,ic:String,panel:String,priceLevel:Number,arr:Array,mix:Mixed,patientStatus:Boolean,created:Date"'

`Running "express:dev" (express) task
Starting background Express server
E:\EXP-proj\generator-restgoose\models\patient.js:15
        mix: { type: Mixed },
                     ^

ReferenceError: Mixed is not defined
    at Object.<anonymous> (E:\EXP-proj\generator-restgoose\models\patient.js:15:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)`

**Comment by vikz91** [comment]
hi azizasm, thanx for communicating the issue.
I haven't given the 'Mixed' identifier in the generator so far. But I too feel it is a much needed feature. So, I will be working on the 'Mixed' data type feature and update the generator soon. Thanks for the heads up.

**Comment by vikz91** [comment]
Hello, thanks to you, I was able to get notified about this issue. This has been solved and updated on github and published on npm @ 0.1.9 . Please update your local copy of the generator.
