### ISSUE TITLE
Typo for Endpoint Summary for Search

### ISSUE THREAD

**Issue by azizasm** [vikz91/generator-mongoose#6]
In docs the Endpoint Summary for Search shows as `SEARCH` but in actual it should be `GET`  ? Please correct me if I wrong.

**Comment by vikz91** [comment]
Hi,
Thanks for noticing the issue. Will get back to it asap.

**Comment by vikz91** [comment]
Hello, thanks to you, I was able to get notified about this issue. This has been solved and updated on github and published on npm @ 0.1.9 . Please update your local copy of the generator.
